config/routes.rb
MineAussieSurfLife::Application.routes.draw do
	resources :welcomes
	resources :wetsuites
	resources :spots
	resources :boards
	resources :users
	resources :surfers
	resources :sessions, only: [:new, :create, :destroy]
  resources :signups, only: [:new, :create, :destroy]
  
	match '/login', 	to: 'sessions#new', 		  via: 'get'
	match '/logout', 	to: 'sessions#destroy',		via: 'delete'
  match '/signup',  to: 'signups#new',         via: 'get'
	match '/signout', to: 'signups#destroy',     via: 'delete'
	
  root 'welcomes#index'

  resources :users do
    collection do
      get 'create'
    end
  end

  

end

app/models/spot.rb
class Spot < ActiveRecord::Base

	validates :spot_name, :location, :spot_type, :wave_direction, :level, :best_swell, :tide, :best_wind,:presence => true
	validates :bottom_type, :frequence, :wave_size, :surfers, :hazards, :presence => false 

end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :set_spot, only: [:show, :edit, :update, :destroy]

  # GET /spots
  # GET /spots.json
  def index
    @spots = Spot.all
  end

  # GET /spots/1
  # GET /spots/1.json
  def show
  end

  # GET /spots/new
  def new
    @spot = Spot.new
  end

  # GET /spots/1/edit
  def edit
  end

  # POST /spots
  # POST /spots.json
  def create
    @spot = Spot.new(spot_params)

    respond_to do |format|
      if @spot.save
        format.html { redirect_to @spot, notice: 'Spot was successfully created.' }
        format.json { render action: 'show', status: :created, location: @spot }
      else
        format.html { render action: 'new' }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spots/1
  # PATCH/PUT /spots/1.json
  def update
    respond_to do |format|
      if @spot.update(spot_params)
        format.html { redirect_to @spot, notice: 'Spot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spots/1
  # DELETE /spots/1.json
  def destroy
    @spot.destroy
    respond_to do |format|
      format.html { redirect_to spots_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spot
      @spot = Spot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spot_params
      params[:spot]
    end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/_form.html.erb
<%= form_for(@spot) do |f| %>
  <% if @spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spot.errors.count, "error") %> prohibited this spot from being saved:</h2>

      <ul>
      <% @spot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spots/edit.html.erb
<h1>Editing spot</h1>

<%= render 'form' %>

<%= link_to 'Show', @spot %> |
<%= link_to 'Back', spots_path %>

app/views/spots/index.html.erb
<h1>Listing spots</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @spots.each do |spot| %>
      <tr>
        <td><%= link_to 'Show', spot %></td>
        <td><%= link_to 'Edit', edit_spot_path(spot) %></td>
        <td><%= link_to 'Destroy', spot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Spot', new_spot_path %>

app/views/spots/new.html.erb
<h1>New spot</h1>

<%= render 'form' %>

<%= link_to 'Back', spots_path %>

app/views/spots/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_spot_path(@spot) %> |
<%= link_to 'Back', spots_path %>