config/routes.rb
MineAussieSurfLife::Application.routes.draw do
	resources :welcomes
	resources :wetsuites
	resources :spots
	resources :boards
	resources :users
	resources :surfers
	resources :sessions, only: [:new, :create, :destroy]
  resources :signups, only: [:new, :create, :destroy]
  
	match '/login', 	to: 'sessions#new', 		  via: 'get'
	match '/logout', 	to: 'sessions#destroy',		via: 'delete'
  match '/signup',  to: 'signups#new',         via: 'get'
	match '/signout', to: 'signups#destroy',     via: 'delete'
	
  root 'welcomes#index'

  resources :users do
    collection do
      get 'create'
    end
  end

  

end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :set_welcome, only: [:show, :edit, :update, :destroy]

  # GET /welcomes
  # GET /welcomes.json
  def index
    @welcomes = Welcome.all
  end

  # GET /welcomes/1
  # GET /welcomes/1.json
  def show
  end

  # GET /welcomes/new
  def new
    @welcome = Welcome.new
  end

  # GET /welcomes/1/edit
  def edit
  end

  # POST /welcomes
  # POST /welcomes.json
  def create
    @welcome = Welcome.new(welcome_params)

    respond_to do |format|
      if @welcome.save
        format.html { redirect_to @welcome, notice: 'Welcome was successfully created.' }
        format.json { render action: 'show', status: :created, location: @welcome }
      else
        format.html { render action: 'new' }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /welcomes/1
  # PATCH/PUT /welcomes/1.json
  def update
    respond_to do |format|
      if @welcome.update(welcome_params)
        format.html { redirect_to @welcome, notice: 'Welcome was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /welcomes/1
  # DELETE /welcomes/1.json
  def destroy
    @welcome.destroy
    respond_to do |format|
      format.html { redirect_to welcomes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_welcome
      @welcome = Welcome.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def welcome_params
      params[:welcome]
    end
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/welcomes/_form.html.erb
<%= form_for(@welcome) do |f| %>
  <% if @welcome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@welcome.errors.count, "error") %> prohibited this welcome from being saved:</h2>

      <ul>
      <% @welcome.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/welcomes/edit.html.erb
<h1>Editing welcome</h1>

<%= render 'form' %>

<%= link_to 'Show', @welcome %> |
<%= link_to 'Back', welcomes_path %>

app/views/welcomes/index.html.erb
<div id="primary" class="container_24">
	  	   <div id="slider">
		   		<ul>
		   			<h2> Stunning Web Designs </h2>
					<h2> You Will Love it </h2>
					<p> We work around the clock </p>
					<button> <%= link_to 'JOIN US', new_user_path %> </button>
				</ul> 		
		   </div>
		   
		   <div id="map">
		   		<section>
					<ul>	 
		   				<h2> Browse x surf spots </h2>
						<li><p> Find new spots, save them as favorites and get notification about the best conditions </p></li>
					</ul>
				</section>
				<img src="images/icons/map.png" alt="Map">
				<section class="grid_8 prefix_8">
						<button> BROWSE NOW </button>
				</section>
			</div>
			
			<div id="menu" class="container_24">
		   		<section>
					<ul>	 
					<li id="profile" class="grid_6 alpha">
						<img src="images/icons/profile.png" alt="ProfLogo">
		   				<h4> Create Your Profile </h4>
						<p> Lets throw a trackie dacks also it'll be gutta. You little ripper avos flamin lets throw a lizard drinking. 
							Gutful of jug where as busy as a big smoke. Grab us a billy as cunning as a bull bar. 
							As cunning as a bonzer flamin as stands out like cubby house. dramas as cunning as a barrack >> </p>
					</li>
					<li class="grid_6">
						<img src="images/icons/community.png" alt="ComLogo">
		   				<h4> Enter The Community </h4>
						<p> Lets throw a trackie dacks also it'll be gutta. You little ripper avos flamin lets throw a lizard drinking. 
							Gutful of jug where as busy as a big smoke. Grab us a billy as cunning as a bull bar. 
							As cunning as a bonzer flamin as stands out like cubby house. dramas as cunning as a barrack >> </p>
					</li>
					<li class="grid_6">
						<img src="images/icons/gps.png" alt="Gps">
		   				<h4> Find Unknown Spots </h4>
						<p> Lets throw a trackie dacks also it'll be gutta. You little ripper avos flamin lets throw a lizard drinking. 
							Gutful of jug where as busy as a big smoke. Grab us a billy as cunning as a bull bar. 
							As cunning as a bonzer flamin as stands out like cubby house. dramas as cunning as a barrack >> </p>
					</li>
					<li id="cloud" class="grid_6 omega">
						<img src="images/icons/cloud.png" alt="Cloud">
		   				<h4> Check Forecasts </h4>
						<p> Lets throw a trackie dacks also it'll be gutta. You little ripper avos flamin lets throw a lizard drinking. 
							Gutful of jug where as busy as a big smoke. Grab us a billy as cunning as a bull bar. 
							As cunning as a bonzer flamin as stands out like cubby house. dramas as cunning as a barrack >> </p>
					</li>
					</ul>
				</section>
			</div>
			
			<div class="container_24">
				<nav id="arrow">
						<img src="images/icons/arrow.png" class="arrowProfile">
						<img src="images/icons/arrow.png" class="arrowCom">
						<img src="images/icons/arrow.png" class="arrowSpot">
					    <img src="images/icons/arrow.png" class="arrowForecast">
				</nav>
				<section id="example">
					<ul>
		   	   		<li class="grid_6 alpha">
			   	   		<a href="#">
				   	  	   <img src="images/profile.jpg" class="profile">
				   		</a>
			   		</li>
					<li class="grid_6">
			   	   		<a href="#">
				   	  	   <img src="images/community.jpg" class="comImg">
				   		</a>
			   		</li>
					<li class="grid_6">
			   	   		<a href="#">
				   	  	   <img src="images/spot.jpg" class="spot">
				   		</a>
			   		</li>
					<li class="grid_6 omega">
			   	   		<a href="#">
				   	  	   <img src="images/forecast.jpg" class="forecast">
				   		</a>
			   		</li>
					</ul> 
				</section>
		   </div> 
	  </div>
	  
  	  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
      <script src="js/scripts.min.js"></script>
	  
	  <%= stylesheet_link_tag "welcome" %>

app/views/welcomes/new.html.erb
<h1>New welcome</h1>

<%= render 'form' %>

<%= link_to 'Back', welcomes_path %>

app/views/welcomes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_welcome_path(@welcome) %> |
<%= link_to 'Back', welcomes_path %>