config/routes.rb
MineAussieSurfLife::Application.routes.draw do
	resources :welcomes
	resources :wetsuites
	resources :spots
	resources :boards
	resources :users
	resources :surfers
	resources :sessions, only: [:new, :create, :destroy]
  resources :signups, only: [:new, :create, :destroy]
  
	match '/login', 	to: 'sessions#new', 		  via: 'get'
	match '/logout', 	to: 'sessions#destroy',		via: 'delete'
  match '/signup',  to: 'signups#new',         via: 'get'
	match '/signout', to: 'signups#destroy',     via: 'delete'
	
  root 'welcomes#index'

  resources :users do
    collection do
      get 'create'
    end
  end

  

end

app/models/wetsuite.rb
class Wetsuite < ActiveRecord::Base
	validates :brand, :presence => true
	validates :thickness, :presence => true
	validates :type, :presence => true
end

app/controllers/wetsuites_controller.rb
class WetsuitesController < ApplicationController
  before_action :set_wetsuite, only: [:show, :edit, :update, :destroy]

  # GET /wetsuites
  # GET /wetsuites.json
  def index
    @wetsuites = Wetsuite.all
  end

  # GET /wetsuites/1
  # GET /wetsuites/1.json
  def show
  end

  # GET /wetsuites/new
  def new
    @wetsuite = Wetsuite.new
  end

  # GET /wetsuites/1/edit
  def edit
  end

  # POST /wetsuites
  # POST /wetsuites.json
  def create
    @wetsuite = Wetsuite.new(wetsuite_params)

    respond_to do |format|
      if @wetsuite.save
        format.html { redirect_to @wetsuite, notice: 'Wetsuite was successfully created.' }
        format.json { render action: 'show', status: :created, location: @wetsuite }
      else
        format.html { render action: 'new' }
        format.json { render json: @wetsuite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wetsuites/1
  # PATCH/PUT /wetsuites/1.json
  def update
    respond_to do |format|
      if @wetsuite.update(wetsuite_params)
        format.html { redirect_to @wetsuite, notice: 'Wetsuite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @wetsuite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wetsuites/1
  # DELETE /wetsuites/1.json
  def destroy
    @wetsuite.destroy
    respond_to do |format|
      format.html { redirect_to wetsuites_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wetsuite
      @wetsuite = Wetsuite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wetsuite_params
      params[:wetsuite]
    end
end

app/helpers/wetsuites_helper.rb
module WetsuitesHelper
end

app/views/wetsuites/_form.html.erb
<%= form_for(@wetsuite) do |f| %>
  <% if @wetsuite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wetsuite.errors.count, "error") %> prohibited this wetsuite from being saved:</h2>

      <ul>
      <% @wetsuite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wetsuites/edit.html.erb
<h1>Editing wetsuite</h1>

<%= render 'form' %>

<%= link_to 'Show', @wetsuite %> |
<%= link_to 'Back', wetsuites_path %>

app/views/wetsuites/index.html.erb
<h1>Listing wetsuites</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @wetsuites.each do |wetsuite| %>
      <tr>
        <td><%= link_to 'Show', wetsuite %></td>
        <td><%= link_to 'Edit', edit_wetsuite_path(wetsuite) %></td>
        <td><%= link_to 'Destroy', wetsuite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wetsuite', new_wetsuite_path %>

app/views/wetsuites/new.html.erb
<h1>New wetsuite</h1>

<%= render 'form' %>

<%= link_to 'Back', wetsuites_path %>

app/views/wetsuites/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_wetsuite_path(@wetsuite) %> |
<%= link_to 'Back', wetsuites_path %>