config/routes.rb
MineAussieSurfLife::Application.routes.draw do
	resources :welcomes
	resources :wetsuites
	resources :spots
	resources :boards
	resources :users
	resources :surfers
	resources :sessions, only: [:new, :create, :destroy]
  resources :signups, only: [:new, :create, :destroy]
  
	match '/login', 	to: 'sessions#new', 		  via: 'get'
	match '/logout', 	to: 'sessions#destroy',		via: 'delete'
  match '/signup',  to: 'signups#new',         via: 'get'
	match '/signout', to: 'signups#destroy',     via: 'delete'
	
  root 'welcomes#index'

  resources :users do
    collection do
      get 'create'
    end
  end

  

end

app/models/surfer.rb
class Surfer < ActiveRecord::Base
	belongs_to :user
end

app/controllers/surfers_controller.rb
class SurfersController < ApplicationController
  before_action :set_surfer, only: [:show, :edit, :update, :destroy]
  before_filter :get_user
  
  def get_user
	@user = User.find(params[:user_id])
  end
  
  # GET /surfers
  # GET /surfers.json
  def index
    @surfers = @user.surfer
  end

  # GET /surfers/1
  # GET /surfers/1.json
  def show
	@surfer = @user.surfers.find(params[:id])
  end

  # GET /surfers/new
  def new
    # @surfer = @user.surfer.new
  end

  # GET /surfers/1/edit
  def edit
	@surfer = @user.surfers.find(params[:id])
  end

  # POST /surfers
  # POST /surfers.json
  def create
    @surfer = @user.surfers.new(surfer_params)

    respond_to do |format|
      if @surfer.save
        format.html { redirect_to [@user, @surfer], notice: 'Surfer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @surfer }
      else
        format.html { render action: 'new' }
        format.json { render json: @surfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surfers/1
  # PATCH/PUT /surfers/1.json
  def update
    respond_to do |format|
      if @surfer.update(surfer_params)
        format.html { redirect_to @surfer, notice: 'Surfer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @surfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surfers/1
  # DELETE /surfers/1.json
  def destroy
    @surfer.destroy
    respond_to do |format|
      format.html { redirect_to surfers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_surfer
      @surfer = Surfer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def surfer_params
      params.require(:surfer).permit(:nickname, :home_spot, :goofy_regular, :style, :best_trick, :user)
    end
end

app/helpers/surfers_helper.rb
module SurfersHelper
end

app/views/surfers/_form.html.erb
<%= form_for([@user, @surfer]) do |f| %>
	
	<%= f.label :"Nick Name" %>
	<%= f.text_field :nickname%> <br />
	<%= f.label :"Home Spot" %>
	<%= f.text_field :home_spot%> <br />
	<%= f.label :"Style"%>
 	<%= f.select :style, ["ClassicShortBoarder", "NewSchoolHighPerformance", "LongBoarder", "OldStyler", "BodyBoarder"] %> <br />
	<%= f.label :"Goofy or Regular"%>
 	<%= f.select :goofy_regular, ["Goofy", "Regular"]%> <br />
	<%= f.label :"Best trick"%>
	<%= f.select :best_trick, ["Barrel", "Cutback", "Floaters", "Roundhouse", "Carving 360","Snap", "Frontside Air", "Backside Air", "Re-entry", "Layback Snap", "Carving", "Bottom Turn", "Air Reverse", "Backside Air Reverse"]%> <br />
  	
	<% if @surfer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@surfer.errors.count, "error") %> prohibited this surfer from being saved:</h2>

      <ul>
      <% @surfer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  	<% end %>

  	<div class="actions">
    	 <%= f.submit %>
  	</div>
<% end %>

app/views/surfers/edit.html.erb
<h1>Editing surfer</h1>

<%= render 'form' %>

<%= link_to 'Show', [@user, surfer] %> |
<%= link_to 'Back', user_surfers_path(@zombie) %>

app/views/surfers/index.html.erb
<h1>Listing surfers</h1>

<% if @user.surfer == nil %>
   <em> Surfer details are not inserted yet.... </em>
   <%= link_to 'Add Surfer', new_user_surfer_path(@user) %> 
<% else %>
<table>
  <thead>
    <tr>
      <th>Nick Name</th>
      <th>Home Spot</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
      <tr>	  	
		<td><%= @user.surfer.nickname %></td>
		<td><%= @user.surfer.home_spot %></td>
        <td><%= link_to 'Edit Surfer', edit_user_surfer_path(@user) %></td>
        <td><%= link_to 'Delete', [@user, surfer], :method => :delete, :class => "surfer", :confirm => "Are you sure ?"%>
      </tr>
  </tbody>
</table>
<%= link_to 'Users List', users_path %>
<% end %>

app/views/surfers/new.html.erb
<h1>Add Surfer details </h1>

<%= render partial: "form", locals: {user: @user} %>

<%= link_to 'Back', user_surfers_path(@user) %>

app/views/surfers/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Surfer <%= @surfer.nickname%> details</h2>

<table>
  <thead>
    <tr>
      <th>Nick Name</th>
	  <th>Home Spot</th>
	  <th>Goofy Or Regular</th>
	  <th>Style</th>
	  <th>Best Trick</th>
    </tr>
  </thead>

  <tbody>
      <tr>
		<td><%= @surfer.nickname %></td>
		<td><%= @surfer.home_spot %></td>
		<td><%= @surfer.goofy_regular %></td>
		<td><%= @surfer.style %></td>
		<td><%= @surfer.best_trick %></td>
      </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_user_surfer_path(@user) %> |
<%= link_to 'Surfer List', user_surfers_path(@user) %>